In [21]:
import torch 
import trimesh
from torch._vmap_internals import vmap

In [16]:
N = 5
def f(x):
    return x ** 2

x = torch.randn(N, requires_grad=True)
y = f(x)
basis_vectors = torch.eye(N)

In [17]:
jacobian_rows = [torch.autograd.grad(y, x, v, retain_graph=True)[0]
                 for v in basis_vectors.unbind()]
jacobian = torch.stack(jacobian_rows)

In [6]:
(torch.rand(5,10)).unbind()

(tensor([0.7475, 0.6231, 0.2283, 0.3291, 0.2330, 0.5594, 0.7185, 0.6130, 0.9051,
         0.4686]),
 tensor([0.7480, 0.8572, 0.3785, 0.3207, 0.5242, 0.6235, 0.1700, 0.3378, 0.9407,
         0.7856]),
 tensor([0.5240, 0.1346, 0.9546, 0.4070, 0.9171, 0.3123, 0.2728, 0.2720, 0.2472,
         0.5011]),
 tensor([0.3984, 0.5078, 0.1888, 0.5931, 0.3870, 0.3611, 0.5308, 0.9830, 0.3591,
         0.6344]),
 tensor([0.6797, 0.0638, 0.1354, 0.6357, 0.8826, 0.9952, 0.2160, 0.9387, 0.1998,
         0.8028]))

In [19]:
def get_vjp(v):
    return torch.autograd.grad(y, x, v)[0]

In [20]:
jacobian_vmap = vmap(get_vjp)(basis_vectors)
assert torch.allclose(jacobian_vmap, jacobian)
print('ok')

ok


/home/nizar/miniconda3/envs/conv_onet/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.vmap is an experimental prototype that is subject to change and/or deletion. Please use at your own risk. There may be unexpected performance cliffs due to certain operators not being implemented. To see detailed performance warnings please use `torch._C._debug_only_display_vmap_fallback_warnings(True) before the call to `vmap`.
  """Entry point for launching an IPython kernel.


In [3]:
import torch
import torch.optim as optim
import numpy as np
import os
import argparse
import time, datetime
import matplotlib; matplotlib.use('Agg')
from src import config, data
from src.checkpoints import CheckpointIO
from collections import defaultdict
import shutil
from tensorboardX import SummaryWriter

In [4]:
cfg = config.load_config('configs/pointcloud/grid.yaml', 'configs/default.yaml')
is_cuda = (torch.cuda.is_available())
device = torch.device("cuda" if is_cuda else "cpu")
train_dataset = config.get_dataset('train', cfg)

In [ ]:
mesh = trimesh.Trimesh(vertices=shape['inputs'], vertex_normals = shape['inputs.normals'])
mesh.export('mesh.ply', vertex_normal = True, include_attributes =True);